<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<!-- <script type="text/javascript" src="./05.自定义Promise函数模块.js"></script> -->
		<!-- <script src="同行的货/lib/Promise.exercise.js" type="text/javascript" charset="utf-8"></script> -->
		<script src="./自定义练习/04.js" type="text/javascript" charset="utf-8"></script>
		<!-- <script type="text/javascript">
			new Promise((resolve, reject) => {
					resolve(5); //尝试成功
					// reject("error"); //尝试失败
				})
				.then(
					value => {
						console.log("成功1---" + value);
						return new Promise((resolve, reject) => {
							resolve(10);
						}).then(
							value => {
								console.log("成功2---" + value);
								return new Promise((resolve, reject) => {
									resolve(10);
								}).then(
									value => {
										console.log("成功3---" + value);
										return new Promise((resolve, reject) => {
											resolve(10);
										}).then(
											value => {
												console.log("成功4   " + value);
												return "结果2";
											}
										)
									},
									reason => {
										console.log('失败1---' + reason);
									}
								)
							},
							reason => {
								console.log('失败2---' + reason);
							}
						)
					},
					reason => {
						console.log('失败3---' + reason);
					}
				).then(
					value => {
						console.log("成功5   " + value);
						return "结果2";
					}
				) 
				.then(
					value => {
						console.log("成功6   " + value);
					}
				)
				.then(
					value => {
						console.log("成功7   " + value);
					}
				)
		</script> -->
		<!-- <script type="text/javascript">
			new Promise((resolve, reject) => {
				
					// resolve("传递成功信息");
					reject("提示错误信息");
				}).then(
					//成功不写	默认值1 => { return 默认值1}
					//成功不写	默认值2 => Promise.resolve(默认值2)
		
					//失败不写 	默认值1 => { throw 默认值1 } 
					//失败不写 	默认值2 => Promise.reject(默认值2)
				).then( 
					value => {
						console.log("默认值传递的内容为:  " + value);
					},
					reason => {
						console.log("默认值传递的内容为1:  " + reason);
						// console.log(Promise.reject);
						return Promise.reject("一错再错触发catch");
					}
				).catch((reason) => { //这是catch处理 其实就是下面.then一致
					console.log(reason);
					// throw reason;
					// return new Promise(() => {});
					//返回了一个 状态为panding的Promise会中断往下执行
				})
				.then(undefined,
					reason => {
						console.log("和上面效果一致");
						console.log("传递的内容为:  " + reason);
					})
		</script> -->
		<script type="text/javascript">
			const p1 = Promise.resolve(2);
			const p2 = Promise.resolve(Promise.resolve(3));
			const p3 = Promise.resolve(Promise.reject(4));
			const pAll = Promise.all([p1,p2])/* .then(
				value => {
					console.log('成功:' + value);
				},
				reason => {
					console.log('失败:' + reason);
				}
			) */
			/* p1.then(val => console.log(val));
			p1.then(val => console.log(val));
			p1.catch(reason => console.log(reason)); */
			
		</script>
	</body>
</html>
